### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by timkelty** [ikappas/vscode-phpcs#181]
After upgrading `brew`, the default `php` version in my PATH is `PHP 7.4.8`.

I now get this error:
```
  ERR Command failed: php /Users/timkelty/.vscode/extensions/fterrag.vscode-php-cs-fixer-0.3.0/php-cs-fixer fix --using-cache=no --rules=@PSR1,@PSR2 /var/folders/h9/6jg75k_n49s0dqv16k94ynfc0000gn/T/tmp-111637oAWXRiDkdof
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.
: Error: Command failed: php /Users/timkelty/.vscode/extensions/fterrag.vscode-php-cs-fixer-0.3.0/php-cs-fixer fix --using-cache=no --rules=@PSR1,@PSR2 /var/folders/h9/6jg75k_n49s0dqv16k94ynfc0000gn/T/tmp-111637oAWXRiDkdof
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)

```

**Comment by timkelty** [comment]
Sorry, this is an issue with php-cs-fixer, not phpcs :)
